/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package waveprojectboi;

import java.awt.*;

/**
 *
 * @author 020022
 */
public class SinPanelwave extends javax.swing.JPanel {

    private double frequency;
    private double amplitude;
    private double wavelength;
    private double omega;

    /**
     * Creates new form SinPanelwave
     */
    public SinPanelwave() {
        initComponents();
        frequency = 1;
        amplitude = 1;
        wavelength = 1;
        omega = 25;
    }
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        double x1 = 0;
        double y1 = 0;
        double x2 = 0;
        double y2 = 0;
        int centerX = this.getWidth()/2;
        int centerY = this.getHeight()/2;
        amplitude = Waveframerider.amplitude;
        frequency = Waveframerider.frequency;
        
        //Graph horizontal ticks
        g.drawLine(0, centerY, this.getWidth(), (int) centerY);
        for(int i = 0; i <= this.getWidth(); i += 10){
            g.drawLine((int) i, centerY - 2, (int) i, centerY + 2);
        }
        //graph vertical ticks
        for(int i = 0; i <= this.getHeight(); i += 10){
            g.drawLine(0, centerY + i, 5, centerY + i);
            g.drawLine(0, centerY - i, 5, centerY - i);
        }
        
        for(; x1 <= this.getWidth(); x1++){
            
            y1 = amplitude * Math.sin(Math.toRadians(frequency * x1));
            g.drawLine((int) x1, (int) (y1 + centerY), (int) x2, (int)(y2 + centerY));
            x2 = x1;
            y2 = y1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
